<?php 
/*
 * LandedCostCalculationAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace LandedCostCalculationAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class CalculateRequestRateOverride implements JsonSerializable {
    /**
     * The rate converted to landedCost DSL
     * @required
     * @var string $formula public property
     */
    public $formula;

    /**
     * The rate section
     * @required
     * @var object $rateSection public property
     */
    public $rateSection;

    /**
     * The type of duty
     * @required
     * @var object $type public property
     */
    public $type;

    /**
     * The rate as written in the source material
     * @var string $rate public property
     */
    public $rate;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $formula       Initialization value for the property $this->formula    
     * @param   object            $rateSection   Initialization value for the property $this->rateSection
     * @param   object            $type          Initialization value for the property $this->type       
     * @param   string            $rate          Initialization value for the property $this->rate       
     */
    public function __construct()
    {
        if(4 == func_num_args())
        {
            $this->formula     = func_get_arg(0);
            $this->rateSection = func_get_arg(1);
            $this->type        = func_get_arg(2);
            $this->rate        = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['formula']     = $this->formula;
        $json['rateSection'] = $this->rateSection;
        $json['type']        = $this->type;
        $json['rate']        = $this->rate;

        return $json;
    }
}