<?php 
/*
 * LandedCostCalculationAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace LandedCostCalculationAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class CalculateBase implements JsonSerializable {
    /**
     * Currency, in ISO 4217 format
     * @required
     * @var object $currency public property
     */
    public $currency;

    /**
     * Transaction date in ISO 8601 format
     * @required
     * @var string $date public property
     */
    public $date;

    /**
     * @todo Write general description for this property
     * @required
     * @var Destination $destination public property
     */
    public $destination;

    /**
     * Type of sale. Can be used to determine applicable tax types
     * @required
     * @var string $entityType public property
     */
    public $entityType;

    /**
     * Terms of sale. Used to determine buyer obligations
     * @required
     * @var string $incoterms public property
     */
    public $incoterms;

    /**
     * @todo Write general description for this property
     * @required
     * @var Shipping $shipping public property
     */
    public $shipping;

    /**
     * @todo Write general description for this property
     * @required
     * @var Source $source public property
     */
    public $source;

    /**
     * @todo Write general description for this property
     * @var array $charges public property
     */
    public $charges;

    /**
     * The discount to apply at the shipment level
     * @var Discount $discount public property
     */
    public $discount;

    /**
     * Constructor to set initial or default values of member properties
     * @param   object            $currency      Initialization value for the property $this->currency   
     * @param   string            $date          Initialization value for the property $this->date       
     * @param   Destination       $destination   Initialization value for the property $this->destination
     * @param   string            $entityType    Initialization value for the property $this->entityType 
     * @param   string            $incoterms     Initialization value for the property $this->incoterms  
     * @param   Shipping          $shipping      Initialization value for the property $this->shipping   
     * @param   Source            $source        Initialization value for the property $this->source     
     * @param   array             $charges       Initialization value for the property $this->charges    
     * @param   Discount          $discount      Initialization value for the property $this->discount   
     */
    public function __construct()
    {
        if(9 == func_num_args())
        {
            $this->currency    = func_get_arg(0);
            $this->date        = func_get_arg(1);
            $this->destination = func_get_arg(2);
            $this->entityType  = func_get_arg(3);
            $this->incoterms   = func_get_arg(4);
            $this->shipping    = func_get_arg(5);
            $this->source      = func_get_arg(6);
            $this->charges     = func_get_arg(7);
            $this->discount    = func_get_arg(8);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['currency']    = $this->currency;
        $json['date']        = $this->date;
        $json['destination'] = $this->destination;
        $json['entityType']  = $this->entityType;
        $json['incoterms']   = $this->incoterms;
        $json['shipping']    = $this->shipping;
        $json['source']      = $this->source;
        $json['charges']     = $this->charges;
        $json['discount']    = $this->discount;

        return $json;
    }
}