<?php
/*
 * LandedCostCalculationAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace LandedCostCalculationAPILib\Models;

/**
 * Charges to include
 */
class ChargeEnum {
    /**
     * TODO: Write general description for this element
     */
    const DUTIES = "duties";

    /**
     * TODO: Write general description for this element
     */
    const FEES = "fees";

    /**
     * TODO: Write general description for this element
     */
    const TAXES = "taxes";

}