<?php 
/*
 * LandedCostCalculationAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace LandedCostCalculationAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Country implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @var string $code public property
     */
    public $code;

    /**
     * @todo Write general description for this property
     * @var string $name public property
     */
    public $name;

    /**
     * @todo Write general description for this property
     * @var string $system public property
     */
    public $system;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $code     Initialization value for the property $this->code  
     * @param   string            $name     Initialization value for the property $this->name  
     * @param   string            $system   Initialization value for the property $this->system
     */
    public function __construct()
    {
        if(3 == func_num_args())
        {
            $this->code   = func_get_arg(0);
            $this->name   = func_get_arg(1);
            $this->system = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['code']   = $this->code;
        $json['name']   = $this->name;
        $json['system'] = $this->system;

        return $json;
    }
}