<?php
/*
 * LandedCostCalculationAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace LandedCostCalculationAPILib\Models;

/**
 * @todo Write general description for this enumeration
 */
class Destination101Enum {
    /**
     * TODO: Write general description for this element
     */
    const AR = "AR";

    /**
     * TODO: Write general description for this element
     */
    const AT = "AT";

    /**
     * TODO: Write general description for this element
     */
    const AU = "AU";

    /**
     * TODO: Write general description for this element
     */
    const AX = "AX";

    /**
     * TODO: Write general description for this element
     */
    const BE = "BE";

    /**
     * TODO: Write general description for this element
     */
    const BG = "BG";

    /**
     * TODO: Write general description for this element
     */
    const BR = "BR";

    /**
     * TODO: Write general description for this element
     */
    const CA = "CA";

    /**
     * TODO: Write general description for this element
     */
    const CC = "CC";

    /**
     * TODO: Write general description for this element
     */
    const CN = "CN";

    /**
     * TODO: Write general description for this element
     */
    const CX = "CX";

    /**
     * TODO: Write general description for this element
     */
    const CY = "CY";

    /**
     * TODO: Write general description for this element
     */
    const CZ = "CZ";

    /**
     * TODO: Write general description for this element
     */
    const DE = "DE";

    /**
     * TODO: Write general description for this element
     */
    const DK = "DK";

    /**
     * TODO: Write general description for this element
     */
    const EE = "EE";

    /**
     * TODO: Write general description for this element
     */
    const ES = "ES";

    /**
     * TODO: Write general description for this element
     */
    const FI = "FI";

    /**
     * TODO: Write general description for this element
     */
    const FR = "FR";

    /**
     * TODO: Write general description for this element
     */
    const GB = "GB";

    /**
     * TODO: Write general description for this element
     */
    const GF = "GF";

    /**
     * TODO: Write general description for this element
     */
    const GG = "GG";

    /**
     * TODO: Write general description for this element
     */
    const GP = "GP";

    /**
     * TODO: Write general description for this element
     */
    const GR = "GR";

    /**
     * TODO: Write general description for this element
     */
    const HR = "HR";

    /**
     * TODO: Write general description for this element
     */
    const HU = "HU";

    /**
     * TODO: Write general description for this element
     */
    const IE = "IE";

    /**
     * TODO: Write general description for this element
     */
    const IM = "IM";

    /**
     * TODO: Write general description for this element
     */
    const IN = "IN";

    /**
     * TODO: Write general description for this element
     */
    const IO = "IO";

    /**
     * TODO: Write general description for this element
     */
    const IT = "IT";

    /**
     * TODO: Write general description for this element
     */
    const JE = "JE";

    /**
     * TODO: Write general description for this element
     */
    const JP = "JP";

    /**
     * TODO: Write general description for this element
     */
    const LT = "LT";

    /**
     * TODO: Write general description for this element
     */
    const LU = "LU";

    /**
     * TODO: Write general description for this element
     */
    const LV = "LV";

    /**
     * TODO: Write general description for this element
     */
    const MC = "MC";

    /**
     * TODO: Write general description for this element
     */
    const MQ = "MQ";

    /**
     * TODO: Write general description for this element
     */
    const MT = "MT";

    /**
     * TODO: Write general description for this element
     */
    const MX = "MX";

    /**
     * TODO: Write general description for this element
     */
    const NF = "NF";

    /**
     * TODO: Write general description for this element
     */
    const NL = "NL";

    /**
     * TODO: Write general description for this element
     */
    const PL = "PL";

    /**
     * TODO: Write general description for this element
     */
    const PR = "PR";

    /**
     * TODO: Write general description for this element
     */
    const PT = "PT";

    /**
     * TODO: Write general description for this element
     */
    const PY = "PY";

    /**
     * TODO: Write general description for this element
     */
    const RE = "RE";

    /**
     * TODO: Write general description for this element
     */
    const RO = "RO";

    /**
     * TODO: Write general description for this element
     */
    const SE = "SE";

    /**
     * TODO: Write general description for this element
     */
    const SG = "SG";

    /**
     * TODO: Write general description for this element
     */
    const SI = "SI";

    /**
     * TODO: Write general description for this element
     */
    const SK = "SK";

    /**
     * TODO: Write general description for this element
     */
    const SM = "SM";

    /**
     * TODO: Write general description for this element
     */
    const TK = "TK";

    /**
     * TODO: Write general description for this element
     */
    const US = "US";

    /**
     * TODO: Write general description for this element
     */
    const UY = "UY";

    /**
     * TODO: Write general description for this element
     */
    const VE = "VE";

}