<?php 
/*
 * LandedCostCalculationAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace LandedCostCalculationAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Destination implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @required
     * @var string $country public property
     */
    public $country;

    /**
     * Destination region of the shipment, in ISO 3166-2 format
     * @var object $region public property
     */
    public $region;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $country   Initialization value for the property $this->country
     * @param   object            $region    Initialization value for the property $this->region 
     */
    public function __construct()
    {
        if(2 == func_num_args())
        {
            $this->country = func_get_arg(0);
            $this->region  = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['country'] = $this->country;
        $json['region']  = $this->region;

        return $json;
    }
}