<?php 
/*
 * LandedCostCalculationAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace LandedCostCalculationAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Duties implements JsonSerializable {
    /**
     * Currency, in ISO 4217 format
     * @required
     * @var object $currency public property
     */
    public $currency;

    /**
     * The harmonized classification code of the product
     * @required
     * @var string $hsCode public property
     */
    public $hsCode;

    /**
     * The country or region that legislates this rate
     * @required
     * @var Destination $jurisdiction public property
     */
    public $jurisdiction;

    /**
     * The rate as written in the source material
     * @required
     * @var string $rate public property
     */
    public $rate;

    /**
     * The type of duty
     * @required
     * @var string $type public property
     */
    public $type;

    /**
     * Constructor to set initial or default values of member properties
     * @param   object            $currency       Initialization value for the property $this->currency    
     * @param   string            $hsCode         Initialization value for the property $this->hsCode      
     * @param   Destination       $jurisdiction   Initialization value for the property $this->jurisdiction
     * @param   string            $rate           Initialization value for the property $this->rate        
     * @param   string            $type           Initialization value for the property $this->type        
     */
    public function __construct()
    {
        if(5 == func_num_args())
        {
            $this->currency     = func_get_arg(0);
            $this->hsCode       = func_get_arg(1);
            $this->jurisdiction = func_get_arg(2);
            $this->rate         = func_get_arg(3);
            $this->type         = func_get_arg(4);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['currency']     = $this->currency;
        $json['hsCode']       = $this->hsCode;
        $json['jurisdiction'] = $this->jurisdiction;
        $json['rate']         = $this->rate;
        $json['type']         = $this->type;

        return $json;
    }
}