<?php
/*
 * LandedCostCalculationAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace LandedCostCalculationAPILib\Models;

/**
 * @todo Write general description for this enumeration
 */
class EntityTypeEnum {
    /**
     * TODO: Write general description for this element
     */
    const B2B = "B2B";

    /**
     * TODO: Write general description for this element
     */
    const B2C = "B2C";

}