<?php 
/*
 * LandedCostCalculationAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace LandedCostCalculationAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Error implements JsonSerializable {
    /**
     * Full error object response
     * @required
     * @var object $error public property
     */
    public $error;

    /**
     * Friendly error response
     * @required
     * @var string $message public property
     */
    public $message;

    /**
     * Constructor to set initial or default values of member properties
     * @param   object            $error     Initialization value for the property $this->error  
     * @param   string            $message   Initialization value for the property $this->message
     */
    public function __construct()
    {
        if(2 == func_num_args())
        {
            $this->error   = func_get_arg(0);
            $this->message = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['error']   = $this->error;
        $json['message'] = $this->message;

        return $json;
    }
}