<?php 
/*
 * LandedCostCalculationAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace LandedCostCalculationAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class GetCountriesListingsResponse implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @required
     * @var Country[] $destination public property
     */
    public $destination;

    /**
     * @todo Write general description for this property
     * @required
     * @var Country[] $source public property
     */
    public $source;

    /**
     * Constructor to set initial or default values of member properties
     * @param   array             $destination   Initialization value for the property $this->destination
     * @param   array             $source        Initialization value for the property $this->source     
     */
    public function __construct()
    {
        if(2 == func_num_args())
        {
            $this->destination = func_get_arg(0);
            $this->source      = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['destination'] = $this->destination;
        $json['source']      = $this->source;

        return $json;
    }
}