<?php 
/*
 * LandedCostCalculationAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace LandedCostCalculationAPILib\Models;

use JsonSerializable;

/**
 * Array of rate information by source country, formatted as for retrieval for Duty Rate retrieval
 */
class GetRateDataResponse implements JsonSerializable {
    /**
     * A description of the harmonized code classification
     * @required
     * @var string $description public property
     */
    public $description;

    /**
     * The harmonized code
     * @required
     * @var string $hsCode public property
     */
    public $hsCode;

    /**
     * A concatenation of the system and harmonized code: `<system>_<harmonizedCode>`
     * @required
     * @var string $name public property
     */
    public $name;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $description   Initialization value for the property $this->description
     * @param   string            $hsCode        Initialization value for the property $this->hsCode     
     * @param   string            $name          Initialization value for the property $this->name       
     */
    public function __construct()
    {
        if(3 == func_num_args())
        {
            $this->description = func_get_arg(0);
            $this->hsCode      = func_get_arg(1);
            $this->name        = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['description'] = $this->description;
        $json['hsCode']      = $this->hsCode;
        $json['name']        = $this->name;

        return $json;
    }
}