<?php 
/*
 * LandedCostCalculationAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace LandedCostCalculationAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class GetTheSystemForACountryResponse implements JsonSerializable {
    /**
     * The system of export classification between the source and destination countries specified
     * @required
     * @var Export $export public property
     */
    public $export;

    /**
     * The system of import classification between the source and destination countries specified
     * @required
     * @var Import $import public property
     */
    public $import;

    /**
     * Constructor to set initial or default values of member properties
     * @param   Export            $export   Initialization value for the property $this->export
     * @param   Import            $import   Initialization value for the property $this->import
     */
    public function __construct()
    {
        if(2 == func_num_args())
        {
            $this->export = func_get_arg(0);
            $this->import = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['export'] = $this->export;
        $json['import'] = $this->import;

        return $json;
    }
}