<?php 
/*
 * LandedCostCalculationAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace LandedCostCalculationAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Items implements JsonSerializable {
    /**
     * Item subtotal
     * @required
     * @var double $amount public property
     */
    public $amount;

    /**
     * Constructor to set initial or default values of member properties
     * @param   double            $amount   Initialization value for the property $this->amount
     */
    public function __construct()
    {
        if(1 == func_num_args())
        {
            $this->amount = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['amount'] = $this->amount;

        return $json;
    }
}