<?php 
/*
 * LandedCostCalculationAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace LandedCostCalculationAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class LandedCost implements JsonSerializable {
    /**
     * Calculated landedCost.  Total of all products, shipping, and applicable duties, taxes, and fees
     * @required
     * @var double $amount public property
     */
    public $amount;

    /**
     * Is shipment cross-border
     * @required
     * @var bool $isCrossBorder public property
     */
    public $isCrossBorder;

    /**
     * @todo Write general description for this property
     * @required
     * @var array $messages public property
     */
    public $messages;

    /**
     * Total of all products and shipping
     * @var double $costInsuranceFreight public property
     */
    public $costInsuranceFreight;

    /**
     * @todo Write general description for this property
     * @var Details $details public property
     */
    public $details;

    /**
     * Total of all applicable duties, taxes, and fees
     * @var double $dutiesTaxesAndFees public property
     */
    public $dutiesTaxesAndFees;

    /**
     * @todo Write general description for this property
     * @var Obligations $obligations public property
     */
    public $obligations;

    /**
     * Constructor to set initial or default values of member properties
     * @param   double            $amount                 Initialization value for the property $this->amount              
     * @param   bool              $isCrossBorder          Initialization value for the property $this->isCrossBorder       
     * @param   array             $messages               Initialization value for the property $this->messages            
     * @param   double            $costInsuranceFreight   Initialization value for the property $this->costInsuranceFreight
     * @param   Details           $details                Initialization value for the property $this->details             
     * @param   double            $dutiesTaxesAndFees     Initialization value for the property $this->dutiesTaxesAndFees  
     * @param   Obligations       $obligations            Initialization value for the property $this->obligations         
     */
    public function __construct()
    {
        if(7 == func_num_args())
        {
            $this->amount               = func_get_arg(0);
            $this->isCrossBorder        = func_get_arg(1);
            $this->messages             = func_get_arg(2);
            $this->costInsuranceFreight = func_get_arg(3);
            $this->details              = func_get_arg(4);
            $this->dutiesTaxesAndFees   = func_get_arg(5);
            $this->obligations          = func_get_arg(6);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['amount']               = $this->amount;
        $json['isCrossBorder']        = $this->isCrossBorder;
        $json['messages']             = $this->messages;
        $json['costInsuranceFreight'] = $this->costInsuranceFreight;
        $json['details']              = $this->details;
        $json['dutiesTaxesAndFees']   = $this->dutiesTaxesAndFees;
        $json['obligations']          = $this->obligations;

        return $json;
    }
}