<?php
/*
 * LandedCostCalculationAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace LandedCostCalculationAPILib\Models;

/**
 * @todo Write general description for this enumeration
 */
class ModeEnum {
    /**
     * TODO: Write general description for this element
     */
    const AIR = "air";

    /**
     * TODO: Write general description for this element
     */
    const GROUND = "ground";

    /**
     * TODO: Write general description for this element
     */
    const OCEAN = "ocean";

}