<?php
/*
 * LandedCostCalculationAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace LandedCostCalculationAPILib\Models;

/**
 * @todo Write general description for this enumeration
 */
class NameEnum {
    /**
     * TODO: Write general description for this element
     */
    const ITEMDISCOUNT = "itemDiscount";

    /**
     * TODO: Write general description for this element
     */
    const ORDERDISCOUNT = "orderDiscount";

}