<?php 
/*
 * LandedCostCalculationAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace LandedCostCalculationAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Obligation implements JsonSerializable {
    /**
     * Buyer's obligation amount
     * @required
     * @var double $amount public property
     */
    public $amount;

    /**
     * Currency, in ISO 4217 format
     * @required
     * @var object $currency public property
     */
    public $currency;

    /**
     * Constructor to set initial or default values of member properties
     * @param   double            $amount     Initialization value for the property $this->amount  
     * @param   object            $currency   Initialization value for the property $this->currency
     */
    public function __construct()
    {
        if(2 == func_num_args())
        {
            $this->amount   = func_get_arg(0);
            $this->currency = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['amount']   = $this->amount;
        $json['currency'] = $this->currency;

        return $json;
    }
}