<?php
/*
 * LandedCostCalculationAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace LandedCostCalculationAPILib\Models;

/**
 * Included when a shipment item qualifies for a special rate, such as NAFTA
 */
class PreferenceProgramEnum {
    /**
     * TODO: Write general description for this element
     */
    const NAFTA = "NAFTA";

}