<?php 
/*
 * LandedCostCalculationAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace LandedCostCalculationAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Request implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @required
     * @var Destination $destination public property
     */
    public $destination;

    /**
     * The harmonized classification code of the product
     * @required
     * @var string $hsCode public property
     */
    public $hsCode;

    /**
     * @todo Write general description for this property
     * @required
     * @var Source $source public property
     */
    public $source;

    /**
     * Constructor to set initial or default values of member properties
     * @param   Destination       $destination   Initialization value for the property $this->destination
     * @param   string            $hsCode        Initialization value for the property $this->hsCode     
     * @param   Source            $source        Initialization value for the property $this->source     
     */
    public function __construct()
    {
        if(3 == func_num_args())
        {
            $this->destination = func_get_arg(0);
            $this->hsCode      = func_get_arg(1);
            $this->source      = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['destination'] = $this->destination;
        $json['hsCode']      = $this->hsCode;
        $json['source']      = $this->source;

        return $json;
    }
}