<?php 
/*
 * LandedCostCalculationAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace LandedCostCalculationAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Response73 implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @required
     * @var Destination $destination public property
     */
    public $destination;

    /**
     * The harmonized classification code of the product
     * @required
     * @var string $hsCode public property
     */
    public $hsCode;

    /**
     * @todo Write general description for this property
     * @required
     * @var Source $source public property
     */
    public $source;

    /**
     * @todo Write general description for this property
     * @required
     * @var Status $status public property
     */
    public $status;

    /**
     * Units used in rate formulas for a given hs code
     * @required
     * @var array $units public property
     */
    public $units;

    /**
     * Constructor to set initial or default values of member properties
     * @param   Destination       $destination   Initialization value for the property $this->destination
     * @param   string            $hsCode        Initialization value for the property $this->hsCode     
     * @param   Source            $source        Initialization value for the property $this->source     
     * @param   Status            $status        Initialization value for the property $this->status     
     * @param   array             $units         Initialization value for the property $this->units      
     */
    public function __construct()
    {
        if(5 == func_num_args())
        {
            $this->destination = func_get_arg(0);
            $this->hsCode      = func_get_arg(1);
            $this->source      = func_get_arg(2);
            $this->status      = func_get_arg(3);
            $this->units       = func_get_arg(4);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['destination'] = $this->destination;
        $json['hsCode']      = $this->hsCode;
        $json['source']      = $this->source;
        $json['status']      = $this->status;
        $json['units']       = $this->units;

        return $json;
    }
}