<?php 
/*
 * LandedCostCalculationAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace LandedCostCalculationAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Shipping implements JsonSerializable {
    /**
     * Cost of shipping
     * @required
     * @var double $cost public property
     */
    public $cost;

    /**
     * Is Shipping method.  Can be used to determine applicable tax types
     * @required
     * @var bool $express public property
     */
    public $express;

    /**
     * Cost of shipping insurance
     * @required
     * @var double $insurance public property
     */
    public $insurance;

    /**
     * Shipping method.  Can be used to determine applicable tax types
     * @var string $mode public property
     */
    public $mode;

    /**
     * Constructor to set initial or default values of member properties
     * @param   double            $cost        Initialization value for the property $this->cost     
     * @param   bool              $express     Initialization value for the property $this->express  
     * @param   double            $insurance   Initialization value for the property $this->insurance
     * @param   string            $mode        Initialization value for the property $this->mode     
     */
    public function __construct()
    {
        if(4 == func_num_args())
        {
            $this->cost      = func_get_arg(0);
            $this->express   = func_get_arg(1);
            $this->insurance = func_get_arg(2);
            $this->mode      = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['cost']      = $this->cost;
        $json['express']   = $this->express;
        $json['insurance'] = $this->insurance;
        $json['mode']      = $this->mode;

        return $json;
    }
}