<?php
/*
 * LandedCostCalculationAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace LandedCostCalculationAPILib\Models;

/**
 * @todo Write general description for this enumeration
 */
class System102Enum {
    /**
     * TODO: Write general description for this element
     */
    const CTCA = "CTCA";

    /**
     * TODO: Write general description for this element
     */
    const CTIN = "CTIN";

    /**
     * TODO: Write general description for this element
     */
    const CTMX = "CTMX";

    /**
     * TODO: Write general description for this element
     */
    const HS = "HS";

    /**
     * TODO: Write general description for this element
     */
    const HTISC = "HTISC";

    /**
     * TODO: Write general description for this element
     */
    const HTS = "HTS";

    /**
     * TODO: Write general description for this element
     */
    const HTSB = "HTSB";

    /**
     * TODO: Write general description for this element
     */
    const MCN = "MCN";

    /**
     * TODO: Write general description for this element
     */
    const STCCED = "STCCED";

    /**
     * TODO: Write general description for this element
     */
    const TARIC = "TARIC";

    /**
     * TODO: Write general description for this element
     */
    const TSCN = "TSCN";

    /**
     * TODO: Write general description for this element
     */
    const TSJP = "TSJP";

}