<?php 
/*
 * LandedCostCalculationAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace LandedCostCalculationAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class TaxDetail implements JsonSerializable {
    /**
     * Tax amount
     * @required
     * @var double $amount public property
     */
    public $amount;

    /**
     * Tax name
     * @required
     * @var string $name public property
     */
    public $name;

    /**
     * Tax basis the rate is applied to
     * @required
     * @var double $taxBasis public property
     */
    public $taxBasis;

    /**
     * Constructor to set initial or default values of member properties
     * @param   double            $amount     Initialization value for the property $this->amount  
     * @param   string            $name       Initialization value for the property $this->name    
     * @param   double            $taxBasis   Initialization value for the property $this->taxBasis
     */
    public function __construct()
    {
        if(3 == func_num_args())
        {
            $this->amount   = func_get_arg(0);
            $this->name     = func_get_arg(1);
            $this->taxBasis = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['amount']   = $this->amount;
        $json['name']     = $this->name;
        $json['taxBasis'] = $this->taxBasis;

        return $json;
    }
}