<?php 
/*
 * LandedCostCalculationAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace LandedCostCalculationAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Unit implements JsonSerializable {
    /**
     * Name of the unit of measure
     * @required
     * @var string $name public property
     */
    public $name;

    /**
     * Value associated with this unit of measure
     * @var double $amount public property
     */
    public $amount;

    /**
     * Total value associated with this unit of measure (amount * quantity)
     * @var double $total public property
     */
    public $total;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $name     Initialization value for the property $this->name  
     * @param   double            $amount   Initialization value for the property $this->amount
     * @param   double            $total    Initialization value for the property $this->total 
     */
    public function __construct()
    {
        if(3 == func_num_args())
        {
            $this->name   = func_get_arg(0);
            $this->amount = func_get_arg(1);
            $this->total  = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['name']   = $this->name;
        $json['amount'] = $this->amount;
        $json['total']  = $this->total;

        return $json;
    }
}